region                      = "eu-north-1"
nxb_version                 = ""
ssm_param_biscuit_secretkey = "NIXBUILD_BISCUIT_SECRETKEY"
ssm_param_ssh_hostkey       = "NIXBUILD_SSH_HOSTKEY"
nxb_server_instance_type    = "c5a.4xlarge"
